--------------------------------------------------------
-- Archivo creado  - domingo-marzo-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESP
--------------------------------------------------------

  CREATE TABLE "RESP" ("ID_RESP" NUMBER(*,0), "PUNT_ALUMNO" NUMBER(7,2), "PUNT_NORM" NUMBER(2,1), "ALUMNO_RUT_ALUMNO" VARCHAR2(11 CHAR), "RESP_CORREG" NUMBER(*,0), "RESPUESTA_ALUMNO" VARCHAR2(1))
REM INSERTING into RESP
SET DEFINE OFF;
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('1','2',null,'12736373-0','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('2','8',null,'12736373-0','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('3','0',null,'12736373-0','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('4','0',null,'12736373-0','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('5','2',null,'12736373-0','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('6','3',null,'12736373-0','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('7','5',null,'12736373-0','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('8','5',null,'12736373-0','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('9','0',null,'12736373-0','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('10','0',null,'12736373-0','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('11','0',null,'12736373-0','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('12','0',null,'12736373-0','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('13','7,5',null,'12736373-0','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('14','7,5',null,'12736373-0','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('15','7,5',null,'12736373-0','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('16','7,5',null,'12736373-0','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('17','0',null,'12736373-0','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('18','0',null,'12736373-0','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('19','0',null,'12736373-0','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('20','0',null,'12736373-0','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('21','2',null,'14654485-1','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('22','8',null,'14654485-1','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('23','2,5',null,'14654485-1','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('24','2,5',null,'14654485-1','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('25','2',null,'14654485-1','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('26','3',null,'14654485-1','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('27','0',null,'14654485-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('28','0',null,'14654485-1','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('29','0',null,'14654485-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('30','0',null,'14654485-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('31','5',null,'14654485-1','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('32','5',null,'14654485-1','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('33','7,5',null,'14654485-1','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('34','0',null,'14654485-1','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('35','0',null,'14654485-1','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('36','0',null,'14654485-1','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('37','0',null,'14654485-1','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('38','0',null,'14654485-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('39','6',null,'14654485-1','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('40','4',null,'14654485-1','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('41','2',null,'17044365-9','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('42','8',null,'17044365-9','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('43','2,5',null,'17044365-9','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('44','2,5',null,'17044365-9','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('45','0',null,'17044365-9','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('46','0',null,'17044365-9','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('47','0',null,'17044365-9','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('48','0',null,'17044365-9','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('49','0',null,'17044365-9','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('50','7',null,'17044365-9','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('51','5',null,'17044365-9','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('52','5',null,'17044365-9','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('53','7,5',null,'17044365-9','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('54','7,5',null,'17044365-9','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('55','7,5',null,'17044365-9','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('56','7,5',null,'17044365-9','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('57','7,5',null,'17044365-9','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('58','7,5',null,'17044365-9','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('59','0',null,'17044365-9','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('60','0',null,'17044365-9','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('61','0',null,'19432987-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('62','8',null,'19432987-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('63','2,5',null,'19432987-3','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('64','2,5',null,'19432987-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('65','0',null,'19432987-3','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('66','0',null,'19432987-3','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('67','0',null,'19432987-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('68','5',null,'19432987-3','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('69','3',null,'19432987-3','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('70','7',null,'19432987-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('71','0',null,'19432987-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('72','5',null,'19432987-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('73','0',null,'19432987-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('74','7,5',null,'19432987-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('75','0',null,'19432987-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('76','0',null,'19432987-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('77','7,5',null,'19432987-3','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('78','7,5',null,'19432987-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('79','0',null,'19432987-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('80','0',null,'19432987-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('81','0',null,'20457649-1','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('82','0',null,'20457649-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('83','0',null,'20457649-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('84','0',null,'20457649-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('85','0',null,'20457649-1','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('86','3',null,'20457649-1','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('87','5',null,'20457649-1','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('88','5',null,'20457649-1','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('89','3',null,'20457649-1','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('90','0',null,'20457649-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('91','0',null,'20457649-1','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('92','0',null,'20457649-1','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('93','0',null,'20457649-1','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('94','0',null,'20457649-1','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('95','7,5',null,'20457649-1','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('96','7,5',null,'20457649-1','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('97','7,5',null,'20457649-1','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('98','7,5',null,'20457649-1','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('99','0',null,'20457649-1','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('100','0',null,'20457649-1','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('101','0',null,'21902099-6','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('102','0',null,'21902099-6','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('103','2,5',null,'21902099-6','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('104','2,5',null,'21902099-6','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('105','2',null,'21902099-6','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('106','3',null,'21902099-6','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('107','5',null,'21902099-6','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('108','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('109','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('110','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('111','5',null,'21902099-6','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('112','5',null,'21902099-6','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('113','7,5',null,'21902099-6','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('114','0',null,'21902099-6','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('115','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('116','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('117','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('118','0',null,'21902099-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('119','6',null,'21902099-6','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('120','4',null,'21902099-6','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('121','2',null,'23747643-3','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('122','8',null,'23747643-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('123','2,5',null,'23747643-3','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('124','2,5',null,'23747643-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('125','0',null,'23747643-3','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('126','3',null,'23747643-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('127','0',null,'23747643-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('128','5',null,'23747643-3','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('129','0',null,'23747643-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('130','7',null,'23747643-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('131','5',null,'23747643-3','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('132','5',null,'23747643-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('133','0',null,'23747643-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('134','7,5',null,'23747643-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('135','0',null,'23747643-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('136','7,5',null,'23747643-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('137','0',null,'23747643-3','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('138','7,5',null,'23747643-3','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('139','0',null,'23747643-3','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('140','4',null,'23747643-3','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('141','0',null,'7333919-7','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('142','8',null,'7333919-7','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('143','2,5',null,'7333919-7','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('144','2,5',null,'7333919-7','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('145','2',null,'7333919-7','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('146','0',null,'7333919-7','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('147','0',null,'7333919-7','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('148','0',null,'7333919-7','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('149','0',null,'7333919-7','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('150','7',null,'7333919-7','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('151','5',null,'7333919-7','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('152','5',null,'7333919-7','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('153','0',null,'7333919-7','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('154','7,5',null,'7333919-7','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('155','0',null,'7333919-7','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('156','7,5',null,'7333919-7','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('157','0',null,'7333919-7','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('158','7,5',null,'7333919-7','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('159','0',null,'7333919-7','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('160','4',null,'7333919-7','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('161','0',null,'8820576-6','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('162','8',null,'8820576-6','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('163','0',null,'8820576-6','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('164','2,5',null,'8820576-6','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('165','0',null,'8820576-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('166','3',null,'8820576-6','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('167','5',null,'8820576-6','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('168','5',null,'8820576-6','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('169','3',null,'8820576-6','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('170','0',null,'8820576-6','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('171','0',null,'8820576-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('172','0',null,'8820576-6','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('173','0',null,'8820576-6','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('174','7,5',null,'8820576-6','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('175','7,5',null,'8820576-6','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('176','0',null,'8820576-6','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('177','7,5',null,'8820576-6','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('178','0',null,'8820576-6','0','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('179','6',null,'8820576-6','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('180','0',null,'8820576-6','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('181','0',null,'8927869-4','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('182','0',null,'8927869-4','0','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('183','2,5',null,'8927869-4','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('184','0',null,'8927869-4','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('185','2',null,'8927869-4','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('186','0',null,'8927869-4','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('187','5',null,'8927869-4','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('188','0',null,'8927869-4','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('189','3',null,'8927869-4','1','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('190','0',null,'8927869-4','0','a');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('191','5',null,'8927869-4','1','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('192','5',null,'8927869-4','1','d');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('193','7,5',null,'8927869-4','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('194','0',null,'8927869-4','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('195','0',null,'8927869-4','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('196','7,5',null,'8927869-4','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('197','0',null,'8927869-4','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('198','7,5',null,'8927869-4','1','b');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('199','0',null,'8927869-4','0','c');
Insert into RESP (ID_RESP,PUNT_ALUMNO,PUNT_NORM,ALUMNO_RUT_ALUMNO,RESP_CORREG,RESPUESTA_ALUMNO) values ('200','4',null,'8927869-4','1','d');
--------------------------------------------------------
--  DDL for Index RESP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESP_PK" ON "RESP" ("ID_RESP")
--------------------------------------------------------
--  Constraints for Table RESP
--------------------------------------------------------

  ALTER TABLE "RESP" MODIFY ("RESP_CORREG" NOT NULL ENABLE)
  ALTER TABLE "RESP" ADD CONSTRAINT "RESP_PK" PRIMARY KEY ("ID_RESP") ENABLE
  ALTER TABLE "RESP" MODIFY ("ALUMNO_RUT_ALUMNO" NOT NULL ENABLE)
  ALTER TABLE "RESP" MODIFY ("ID_RESP" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table RESP
--------------------------------------------------------

  ALTER TABLE "RESP" ADD CONSTRAINT "RESP_ALUMNO_FK" FOREIGN KEY ("ALUMNO_RUT_ALUMNO") REFERENCES "ALUMNO" ("RUT_ALUMNO") ENABLE
