--------------------------------------------------------
-- Archivo creado  - domingo-marzo-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OPCION
--------------------------------------------------------

  CREATE TABLE "OPCION" ("ID_ALT" NUMBER(*,0), "NOMBRE_ALT" VARCHAR2(2), "PORCENTAJE" NUMBER(*,0), "PREGUNTA_ID_PREG" NUMBER(*,0), "ES_CORRECTO" NUMBER(*,0))
REM INSERTING into OPCION
SET DEFINE OFF;
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('1','a','20','1','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('2','b','0','1','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('3','c','0','1','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('4','d','80','1','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('5','a','50','2','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('6','b','50','2','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('7','c','0','2','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('8','d','0','2','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('9','a','0','3','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('10','b','0','3','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('11','c','40','3','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('12','d','60','3','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('13','a','50','4','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('14','b','0','4','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('15','c','50','4','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('16','d','0','4','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('17','a','30','5','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('18','b','70','5','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('19','c','0','5','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('20','d','0','5','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('21','a','0','6','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('22','b','0','6','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('23','c','50','6','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('24','d','50','6','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('25','a','0','7','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('26','b','25','7','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('27','c','0','7','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('28','d','75','7','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('29','a','50','8','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('30','b','50','8','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('31','c','0','8','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('32','d','0','8','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('33','a','50','9','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('34','b','50','9','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('35','c','0','9','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('36','d','0','9','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('37','a','0','10','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('38','b','60','10','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('39','c','0','10','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('40','d','40','10','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('41','a','20','11','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('42','b','0','11','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('43','c','0','11','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('44','d','80','11','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('45','a','50','12','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('46','b','50','12','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('47','c','0','12','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('48','d','0','12','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('49','a','0','13','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('50','b','0','13','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('51','c','40','13','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('52','d','60','13','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('53','a','50','14','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('54','b','0','14','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('55','c','50','14','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('56','d','0','14','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('57','a','30','15','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('58','b','70','15','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('59','c','0','15','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('60','d','0','15','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('61','a','0','16','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('62','b','0','16','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('63','c','50','16','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('64','d','50','16','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('65','a','0','17','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('66','b','25','17','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('67','c','0','17','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('68','d','75','17','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('69','a','50','18','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('70','b','50','18','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('71','c','0','18','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('72','d','0','18','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('73','a','50','19','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('74','b','50','19','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('75','c','0','19','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('76','d','0','19','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('77','a','0','20','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('78','b','60','20','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('79','c','0','20','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('80','d','40','20','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('81','a','50','21','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('82','b','0','21','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('83','a','50','22','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('84','b','0','22','0');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('85','a','25','23','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('86','b','25','23','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('87','c','25','23','1');
Insert into OPCION (ID_ALT,NOMBRE_ALT,PORCENTAJE,PREGUNTA_ID_PREG,ES_CORRECTO) values ('88','d','25','23','1');
--------------------------------------------------------
--  DDL for Index OPCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPCION_PK" ON "OPCION" ("ID_ALT")
--------------------------------------------------------
--  Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "OPCION" MODIFY ("ES_CORRECTO" NOT NULL ENABLE)
  ALTER TABLE "OPCION" ADD CONSTRAINT "OPCION_PK" PRIMARY KEY ("ID_ALT") ENABLE
  ALTER TABLE "OPCION" MODIFY ("PREGUNTA_ID_PREG" NOT NULL ENABLE)
  ALTER TABLE "OPCION" MODIFY ("ID_ALT" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "OPCION" ADD CONSTRAINT "OPCION_PREGUNTA_FK" FOREIGN KEY ("PREGUNTA_ID_PREG") REFERENCES "PREGUNTA" ("ID_PREG") ENABLE
